# Generated by Django 3.2 on 2022-06-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='genres',
        ),
        migrations.AddField(
            model_name='actor',
            name='genres',
            field=models.ManyToManyField(blank=True, max_length=250, to='movies.Genre'),
        ),
    ]
