# Generated by Django 3.2 on 2022-06-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_actor_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='short_description',
            field=models.CharField(blank=True, max_length=350, verbose_name='Short description'),
        ),
    ]
